site_name: mc.py docs
site_description: 'Документация фреймворка VKWave'
site_url: https://jieggii.github.io/mc.py
site_author: 'jieggii'

repo_name: 'jieggii/mc.py'
repo_url: 'https://github.com/jieggii/mc.py'

theme: material
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets